config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, controllers: {
                   sessions: 'users/sessions', 
                   registrations: 'users/registrations'}  
  resources :carts
  get 'cart/index'
  root to: "home#index"
  resources :orderitems
  resources :orders
  resources :addresses
  resources :users
  resources :products
  resources :cart
  
  get 'productmanu/:Manu' => 'products#showbymanu', :as => :product_manu
  get 'productpricerange/:Vatprice' => 'products#showbyprice', :as => :product_price
  
  #get '/cart/add/:id' => 'cart#add', :as => :
  get '/orderitems/create/:id' => 'orderitems#create', :as => :orderitem_create
  delete '/orderitems.id' => 'orderitems#destroy', :as => :orderitem_delete
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderitems
    has_many :products, through: :orderitems
    
    def add_product(product)
        current_item = orderitems.find_by(product_id: product.id)
        if current_item
         if   current_item.quantity == nil
              current_item.quantity = 1
         end
          current_item.quantity +=1
          current_item.subtotal = product.vatprice*current_item.quantity
        else
            current_item = orderitems.build(product_id: product.id);
            current_item.quantity = 1
            current_item.subtotal = product.vatprice
        end
        current_item
    end
    
    def cart_total
        orderitems.to_a.sum{|orderitem| orderitem.subtotal}
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end
  
  def show
 # @orderitems=current_order.orderitems
  end
  
  def add
    #@order = current_order
    #@order.save
    #@orderitem = @order.orderitems.new(params[:product_id])#(order_item_params)
    #@order.save
    #session[:order_id] = @order.id
    
     product_id = params[:id].at(-1).to_i
        cart = session[:cart] || {}
        cart[product_id] ? cart[product_id] += 1 : cart[product_id] = 1
        session[:cart] = cart
        
    
    #id=params[:id]
    #cart = session[:cart] ||= {}
    #cart[id] = (cart[id] || 0) + 1
    #@cart = session[:cart]
    redirect_to :action => :index #:index
  end
  
  def remove
    @order = current_order
    @orderitem = @order.Orderitem.find([params:id])
    @orderitem.destroy
    @orderitems = @order.orderitems
    #id=params[:id]
    #cart = session[:cart]
    #cart.delete[id]
    
    redirect_to :action => :index
  end
  
  def clear
   session[:cart] = nil
   redirect_to :action => :index
  end
  
  def order_item_params
      params.require(:orderitem).permit(:product_id) #(:order_id, :product_id, :quantity, :subtotal)
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    #@carts.carttotal = Cart.orderitems.to_a.sum{|orderitem| orderitem.subtotal}
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    #@cart.carttotal = Cart.carttotal
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    if @cart.id = session[:cart_id]
    @cart.destroy 
    #session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to "/products", notice: 'You have no items in cart' }
      format.json { head :no_content }
      end
    end
  end
   

  #private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<%= @cart.cart_total%>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
  <p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      
      <th>&nbspCart_id</th>
      <th>&nbspCart total</th>
      
    </tr>
  </thead>

  <tbody>
    <%  @carts.each do |cart| %>
      <tr>
        <td><%= cart.id %></td>
        <td><%= cart.cart_total %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Shopping Cart</h1>

<table>
  <thead>
    <tr>
      
      <th>Item</th>
      <th> Price</th>
      <th> Quantity</th>
      <th>&nbspItems Total</th>
      
    </tr>
  </thead>

  <tbody>
    <%  @cart.orderitems.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.product.vatprice %></td>
        <td><%= item.quantity %></td>
        <td><%= item.subtotal %></td>
        <td><%= link_to 'Remove Item', "/orderitems/#{item.id}",  method: :delete, data:{ confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Edit', edit_cart_path(@cart) %></td>
       
      </tr>
    <% end %>
    <tr><td>Total Cart Amount <%= @cart.cart_total %></td>
     <td><%= link_to 'Destroy Cart', @cart, method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
  </tbody>
</table>
<%= button_to "CONTINUE SHOPPING", "/products", :method => :get, :form_class => "my_class" %>
<%= button_to "GO TO CHECKOUT", "/orders/new", :method => :get, :form_class => "my_class" %>

<br>
<% if current_user!=nil %>
        <% if current_user.admin? %>
<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>
<%end%>
<%end%>